name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm init -y
      - run: npm install electron
      - run: echo "console.log('test')" > main.js
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: main.js
